name: Node.js CI
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: ./.github/workflows/continuous-integration-workflow.yml
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}