name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: lugovczov
          reponame: lugovczov/days-in-quarter@master
          token: ${{ secrets.GITHUB_REPO_TOKEN }}